# Generated by Django 5.0.1 on 2025-01-13 08:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIModelTrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('FREELANCER_REC', 'Freelancer Recommendation'), ('WORK_VALIDATION', 'Work Validation')], max_length=20)),
                ('training_data', models.JSONField(blank=True, null=True)),
                ('label', models.IntegerField(blank=True, null=True)),
                ('training_accuracy', models.FloatField(blank=True, null=True)),
                ('training_loss', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(default='v1.0', max_length=20)),
                ('training_data_size', models.IntegerField(default=0)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_used_for_training', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'AI Model Training Logs',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ai_models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ai_models.aimodel')),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_embedding', models.JSONField(default=list)),
                ('task_history_embedding', models.JSONField(default=list)),
                ('performance_score', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
